"""Snapshot of every HTTP route, so a refactor cannot silently drop or rename an endpoint."""

from app.main import app

EXPECTED_ROUTES = {
    "DELETE /api/batches/{batch_id}/grants/{grant_id}",
    "DELETE /api/runs/{batch_id}/grants/{grant_id}",
    "DELETE /api/teams/{team_id}",
    "DELETE /api/teams/{team_id}/members/{user_id}",
    "GET /api/activity",
    "GET /api/artifacts/{task_id}/{relative_path:path}",
    "GET /api/auth/config",
    "GET /api/auth/me",
    "GET /api/batches",
    "GET /api/batches/{batch_id}",
    "GET /api/batches/{batch_id}/tasks",
    "GET /api/batches/{batch_id}/tasks/{task_id}",
    "GET /api/batches/{batch_id}/tasks/{task_id}/export",
    "GET /api/batches/{batch_id}/tasks/{task_id}/feedback",
    "GET /api/catalog",
    "GET /api/datasets",
    "GET /api/datasets/{dataset_id}",
    "GET /api/datasets/{dataset_id}/shares",
    "GET /api/datasets/{dataset_id}/sync-preview",
    "GET /api/datasets/{dataset_id}/tasks/{task_definition_id}",
    "GET /api/datasets/{dataset_id}/tasks/{task_definition_id}/export",
    "GET /api/directory",
    "GET /api/health",
    "GET /api/jobs",
    "GET /api/jobs/{job_id}",
    "GET /api/overview",
    "GET /api/presets",
    "GET /api/ready",
    "GET /api/providers",
    "GET /api/providers/models",
    "GET /api/runs",
    "GET /api/runs/{batch_id}/tasks/{task_id}/export",
    "GET /api/runs/{batch_id}/tasks/{task_id}/feedback",
    "GET /api/runs/{run_id}",
    "GET /api/runs/{run_id}/tasks",
    "GET /api/runs/{run_id}/tasks/{task_id}",
    "GET /api/taxonomy",
    "GET /api/teams",
    "GET /api/users",
    "GET /api/workflows",
    "GET /docs",
    "GET /docs/oauth2-redirect",
    "GET /openapi.json",
    "GET /redoc",
    "GET /{full_path:path}",
    "HEAD /docs",
    "HEAD /docs/oauth2-redirect",
    "HEAD /openapi.json",
    "HEAD /redoc",
    "PATCH /api/taxonomy/proposals/{proposal_id}",
    "PATCH /api/teams/{team_id}",
    "PATCH /api/users/{user_id}",
    "POST /api/analytics/compare",
    "POST /api/analytics/query",
    "POST /api/auth/login",
    "POST /api/auth/logout",
    "POST /api/auth/signup",
    "POST /api/batches",
    "POST /api/batches/{batch_id}/cancel",
    "POST /api/batches/{batch_id}/grants",
    "POST /api/batches/{batch_id}/pause",
    "POST /api/batches/{batch_id}/reconcile",
    "POST /api/batches/{batch_id}/resume",
    "POST /api/batches/{batch_id}/start",
    "POST /api/batches/{batch_id}/sync",
    "POST /api/batches/{batch_id}/tasks/{task_id}/feedback",
    "POST /api/datasets",
    "POST /api/datasets/{dataset_id}/archive",
    "POST /api/datasets/{dataset_id}/import",
    "POST /api/datasets/{dataset_id}/import-zip",
    "POST /api/datasets/{dataset_id}/restore",
    "POST /api/datasets/{dataset_id}/sync-preview",
    "POST /api/imports/zip/validate",
    "POST /api/jobs/{job_id}/retry",
    "POST /api/presets",
    "POST /api/providers/models/sync",
    "POST /api/runs",
    "POST /api/runs/{batch_id}/grants",
    "POST /api/runs/{batch_id}/reconcile",
    "POST /api/runs/{batch_id}/tasks/{task_id}/feedback",
    "POST /api/runs/{run_id}/archive",
    "POST /api/runs/{run_id}/cancel",
    "POST /api/runs/{run_id}/configure",
    "POST /api/runs/{run_id}/pause",
    "POST /api/runs/{run_id}/rerun",
    "POST /api/runs/{run_id}/restore",
    "POST /api/runs/{run_id}/resume",
    "POST /api/runs/{run_id}/start",
    "POST /api/runs/{run_id}/sync",
    "POST /api/tasks/{task_definition_id}/archive",
    "POST /api/tasks/{task_definition_id}/restore",
    "POST /api/taxonomy/candidates/{candidate_id}/approve",
    "POST /api/taxonomy/candidates/{candidate_id}/reject",
    "POST /api/taxonomy/consolidate",
    "POST /api/taxonomy/proposals",
    "POST /api/taxonomy/proposals/{proposal_id}/feedback",
    "POST /api/teams",
    "POST /api/teams/{team_id}/members",
    "POST /api/users",
    "PUT /api/datasets/{dataset_id}/shares",
}


def registered_routes():
    return {
        f"{method} {route.path}" for route in app.routes if hasattr(route, "methods") for method in route.methods or ()
    }


def test_route_inventory_is_unchanged():
    routes = registered_routes()
    assert routes - EXPECTED_ROUTES == set(), "New routes: add them to EXPECTED_ROUTES deliberately"
    assert EXPECTED_ROUTES - routes == set(), "Routes disappeared"


def test_single_page_fallback_is_registered_last():
    assert app.routes[-1].path == "/{full_path:path}"
